spring.application.name=AICONTENT-SERVICE

server.port:8085

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
gemini.api.key=AIzaSyCZ__0VMMmxIV3Q1UjV5dMP-DHHdk89JtE


spring.datasource.url=jdbc:mysql://localhost:3306/resume_builder
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update