spring.application.name=TEMPLATE-SERVICE
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/resume_builder
spring.datasource.username=root
spring.datasource.password=Root@123
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

